name: test

on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/build.yaml
      - fixtures/**
  push:
    paths:
      - .github/workflows/test.yaml
      - .github/workflows/build.yaml
      - fixtures/**
    branches:
      - v1
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  go-version:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: go-version
        run: echo "go-version=$(sed -ne '/^go /s/^go //p' go.mod)" >> "$GITHUB_OUTPUT"
        working-directory: fixtures

  build:
    needs: go-version
    uses: ./.github/workflows/build.yaml
    with:
      context: fixtures
      build-args: |
        go_version=${{ needs.go-version.outputs.go-version }}

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: docker run --rm 'ghcr.io/${{ github.repository }}@${{ needs.build.outputs.digest }}'
